---
web_host: bitraft.gempir.com
cookie_domain: gempir.com
api_host: bitraft-api.gempir.com
grafana_host: grafana.gempir.com

ansible_python_interpreter: /usr/bin/python3

postgresql_databases:
  - name: bitraft
postgresql_users:
  - name: bitraft
    password: "{{ bitraft_postgres_password }}"

prometheus_global:
  scrape_interval: 15s

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9100"
  - job_name: "caddy"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:2019"
  - job_name: "postgres"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9187"

prometheus_postgres_dbname: bitraft