---
  - name: Create commander user
    user:
      name: commander
      shell: /bin/bash
      groups: 
        - bitraft
      append: yes

  - name: Install Service
    template: 
      src: templates/service.j2 
      dest: /etc/systemd/system/commander.service