name: Deploy Bot

on:
  workflow_dispatch:

jobs:
  refresh:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build & Upload image
        run: |
          docker build . -t ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}/bot
          docker login rg.fr-par.scw.cloud -u nologin -p ${{ secrets.SCALEWAY_SECRET }}
          docker push ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}/bot