name: Deploy Bot

on:
  workflow_dispatch:

jobs:
  refresh:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build & Upload image
        run: |
          docker build . -t ${{ secrets.DOCKERIZE_TAG }}
          docker login -u ${{ secrets.DOCKERIZE_USERNAME }} -p ${{ secrets.DOCKERIZE_PASSWORD }} reg.dockerize.io
          docker push ${{ secrets.DOCKERIZE_TAG }}