name: Refresh

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Run refresh
        run: go run cmd/refresh/main.go
        env:
          SCALEWAY_SECRET: ${{ env.SCALEWAY_SECRET }}
          TWITCH_OAUTH: ${{ env.TWITCH_OAUTH }}
          TWITCH_USERNAME: ${{ env.TWITCH_USERNAME }}
          NEXT_PUBLIC_VERCEL_ENV: ${{ env.NEXT_PUBLIC_VERCEL_ENV }}
          NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}
          TWITCH_CLIENT_SECRET: ${{ env.SCALEWAY_SECRET }}
          TWITCH_CLIENT_ID: ${{ env.TWITCH_CLIENT_ID }}
          NEXT_PUBLIC_TWITCH_CLIENT_ID: ${{ env.NEXT_PUBLIC_TWITCH_CLIENT_ID }}
          PLANETSCALE_DB: ${{ env.PLANETSCALE_DB }}
          PLANETSCALE_DB_PASSWORD: ${{ env.PLANETSCALE_DB_PASSWORD }}
          PLANETSCALE_DB_USERNAME: ${{ env.PLANETSCALE_DB_USERNAME }}
          PLANETSCALE_DB_HOST: ${{ env.PLANETSCALE_DB_HOST }}
          SECRET: ${{ env.SECRET }}
