name: Refresh

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Run refresh
        run: go run cmd/refresh/main.go
        env:
          TWITCH_OAUTH: ${{ secrets.TWITCH_OAUTH }}
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
          NEXT_PUBLIC_VERCEL_ENV: ${{ secrets.NEXT_PUBLIC_VERCEL_ENV }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          PLANETSCALE_DB: ${{ secrets.PLANETSCALE_DB }}
          PLANETSCALE_DB_PASSWORD: ${{ secrets.PLANETSCALE_DB_PASSWORD }}
          PLANETSCALE_DB_USERNAME: ${{ secrets.PLANETSCALE_DB_USERNAME }}
          PLANETSCALE_DB_HOST: ${{ secrets.PLANETSCALE_DB_HOST }}
          SECRET: ${{ secrets.SECRET }}
