name: Refresh

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run refresh
        run: go run cmd/refresh/main.go
